name: OnePlus_13T
on:
  workflow_dispatch:
    inputs:
      enable_feature_x:
        description: "是否启用KPM"
        required: false
        default: false
        type: boolean
      enable_feature_y:
        description: "跳过版本比较"
        required: false
        default: false
        type: boolean
      enable_feature_z:
        description: "不发布release"
        required: false
        default: true
        type: boolean
  
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CCACHE_DIR: /home/runner/.ccache  
      CCACHE_MAXSIZE: 8G
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: Configure Git
        run: |
         git config --global user.name "44C38B8"
         git config --global user.email "b2762537725@163.com"

      - name: Install dependencies
        run: |
          sudo apt update 
          sudo apt install -y python3 git curl
          sudo apt install -y python3 git curl ccache
          sudo apt install -y zip

      - name: Compare Version
        if: ${{!inputs.enable_feature_y}}
        id: check
        run: |
          git clone https://github.com/SukiSU-Ultra/SukiSU-Ultra.git SUKI/
          cd SUKI
          KSU_GIT_VERSION=$(git rev-list --count HEAD)
          KSU_VERSION=$((37185 + KSU_GIT_VERSION))
          LATEST_TAG=$(git ls-remote --tags https://github.com/44C38B8/oneplus13_a5p_sukisu.git | tail -n1 | sed 's/.*\///')
          echo "当前版本：$LATEST_TAG"
          echo "最新版本：$KSU_VERSION"
          if [ $LATEST_TAG -eq $KSU_VERSION ];then
            echo "should_cancel=yes" >> $GITHUB_OUTPUT
          fi
          cd ..

      - name: Restore ccache
        if: steps.check.outputs.should_cancel != 'yes'
        uses: actions/cache@v3
        with:
          path: /home/runner/.ccache
          key: ccache-${{ runner.os }}-${{ github.ref }}
          restore-keys: |
            ccache-${{ runner.os }}-

      - name: Install repo tool
        if: steps.check.outputs.should_cancel != 'yes'
        run: |
         curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
         chmod a+x ~/repo
         sudo mv ~/repo /usr/local/bin/repo

      - name: Initialize repo and sync
        if: steps.check.outputs.should_cancel != 'yes'
        run: |
         mkdir kernel_workspace && cd kernel_workspace
         repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b refs/heads/oneplus/sm8750 -m oneplus_13t_b.xml --depth=1
         repo --trace sync -c -j$(nproc --all) --no-tags
         rm kernel_platform/common/android/abi_gki_protected_exports_* || echo "No protected exports!"
         rm kernel_platform/msm-kernel/android/abi_gki_protected_exports_* || echo "No protected exports!"
            
      - name: Set up SukiSU
        if: steps.check.outputs.should_cancel != 'yes'
        run: |
         echo DATE=$(date +%F) >> $GITHUB_ENV
         cd kernel_workspace/kernel_platform
         curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s builtin
         cd ./KernelSU
         KSU_VERSION=$(expr $(/usr/bin/git rev-list --count main) "+" 37185)
         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
         export KSU_VERSION=$KSU_VERSION
         # sed -i "s/DKSU_VERSION=12800/DKSU_VERSION=${KSU_VERSION}/" kernel/Makefile 
         awk -v old='v$1-$(shell cd $(KSU_SRC); $(GIT_BIN) rev-parse --short=8 HEAD)@$(shell cd $(KSU_SRC); $(GIT_BIN) rev-parse --abbrev-ref HEAD)' -v new='v$1-$(KSU_VERSION)-酷安@骁龙8至尊版' '
             index($0, old) {
                 $0 = substr($0, 1, index($0, old)-1) new substr($0, index($0, old) + length(old))
             }
             { print }
         ' kernel/Kbuild > kernel/Kbuild.tmp && mv kernel/Kbuild.tmp kernel/Kbuild
         # awk -v old='KSU_VERSION := $(shell expr 40000 + $(KSU_GITHUB_VERSION_COMMIT) - 2815)' -v new='KSU_VERSION := $(shell expr 10000 + $(KSU_GITHUB_VERSION_COMMIT) + 700)' '
             # index($0, old) {
                 # $0 = substr($0, 1, index($0, old)-1) new substr($0, index($0, old) + length(old))
             # }
             # { print }
         # ' kernel/Makefile > kernel/Makefile.tmp && mv kernel/Makefile.tmp kernel/Makefile

      - name: Set up susfs
        if: steps.check.outputs.should_cancel != 'yes'
        run: |
           cd kernel_workspace
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android15-6.6
           git clone https://github.com/SukiSU-Ultra/SukiSU_patch.git

           cd kernel_platform        
           cp ../susfs4ksu/kernel_patches/50_
